### ISSUE TITLE
Add 1D interpolation features

### ISSUE THREAD

**Issue by PierreRaybaut** [Codra-Ingenierie-Informatique/DataLab#20]
In Issue #15, @marcel-goldschen-ohm mentioned the fact that a spline fit feature would be a nice addition to DataLab.
The purpose of this Issue is to add spline interpolation and other interpolation techniques to a new "Processing>Interpolation" feature.

**Comment by PierreRaybaut** [comment]
Thanks for sharing this code, I was about to use `scipy.interpolate.splev` as well, so it sure helps to see how you use it in order to wrap it accordingly into DataLab.

Some thoughts:
* `xspline` will be optional, otherwise it could be entered as `xmin`, `xmax` , `numpoints` for example
* `xknots`: same as `xspline`
* `n_segments` will also be an optional parameter (and mutually exclusive with `xknots`)

**Comment by marcel-goldschen-ohm** [comment]
I think there may be some confusion with my terrible choice of name `xspline`. Perhaps I should have called it `xeval` or `xoutput` instead? The idea is that the spline is optimized for all (`xdata`, `ydata`), but can optionally be evaluated for a different set of x-values (`xspline`). Usually this is not needed and `xspline` defaults to `xdata`, but a use case would be if you wanted a spline to go through all points but not be influenced by some artifact.

I agree with you that `n_segments` is not needed as `xknots=np.linspace(xmax, xmin, n_segments+1)` takes care of that.

**Comment by PierreRaybaut** [comment]
@marcel-goldschen-ohm, thanks again for 1. motivating the introduction of this feature, 2. providing some insights on how to implement the spline method.

A resampling feature has also been added (see Issue #21).

In the near future, if you want to contribute more directly to the project, we have two options:

1. You may write new features in DataLab's base code, or fix things and suggest it using a pull request
2. Also, you may contribute by writing a plugin: once the feature is stable, it will be easy to transpose it inside DataLab's base code. I could guide you through all the steps: how to write a new plugin, how to implement your processing feature inside a plugin, or how to populate the "Plugins" menu of the application, and so on. As for the integration to the code base, once again, I could guide you through it if you want to.

Anyway, thanks and hoping to see you soon.

**Comment by marcel-goldschen-ohm** [comment]
Happy to help out. And kudos on DataLab, it seems like a tour de force at first glance. I've also got some stuff in the works right now that might be worth chatting with you about at some point in the near future.

Cheers

**Comment by PierreRaybaut** [comment]
Hello @marcel-goldschen-ohm,

Thank you so much for your kind words about DataLab! It's always great to hear positive feedback, and I'm glad you see it as a tour de force.

I'm definitely interested in hearing more about the projects you're working on and would love to chat about them soon. Collaborative discussions often lead to exciting ideas and developments, so I'm looking forward to our conversation.

Also, if you're enthusiastic about DataLab, please feel free to share it with your colleagues and friends. Spreading the word helps us grow and evolve, and we appreciate your support in this.

Looking forward to our future discussions!

Cheers
